const ADD_VIDEO = 'WS_ADD_VIDEO';
const JOIN_ROOM = 'WS_JOIN_ROOM';
const UPDATE_ROOM = 'WS_UPDATE_ROOM';
const REMOVE_VIDEO = 'WS_REMOVE_VIDEO';

module.exports = {
    UPDATE_ROOM,
    ADD_VIDEO,
    JOIN_ROOM,
    REMOVE_VIDEO
}