export const SET_NAME = 'SET_NAME';
export const SET_IS_LOGGED = 'SET_IS_LOGGED';
export const SET_URL_VIDEO = 'SET_URL_VIDEO';
export const SET_SUGGESTED_VIDEOS = 'SET_SUGGESTED_VIDEOS';
export const SET_VIDEOS = 'SET_VIDEOS';
export const SET_LOADING_VIDEOS = 'SET_LOADING_VIDEOS';
export const SET_ROOM = 'SET_ROOM';
export const SET_LOADING = 'SET_LOADING';
export const SET_PLAY_VIDEO = 'SET_PLAY_VIDEO';
export const SET_SEEK_VIDEO = 'SET_SEEK_VIDEO';
export const SET_IS_PLAYING = 'SET_IS_PLAYING';
export const SET_CHAT = 'SET_CHAT';
export const SET_PROGRESS_VIDEO = 'SET_PROGRESS_VIDEO';

export const WS_JOIN_ROOM = 'WS_JOIN_ROOM';
export const WS_ADD_VIDEO = 'WS_ADD_VIDEO';
export const WS_GET_VIDEO = 'WS_GET_VIDEO';
export const WS_UPDATE_ROOM = 'WS_UPDATE_ROOM';
export const WS_REMOVE_VIDEO = 'WS_REMOVE_VIDEO';
export const WS_VIEW_VIDEO = 'WS_VIEW_VIDEO';
export const WS_SEND_PLAYER_STATE = 'WS_SEND_PLAYER_STATE';
export const WS_SEND_PROGRESS = 'WS_SEND_PROGRESS';
export const WS_NOTIFY_MESSAGE = 'WS_NOTIFY_MESSAGE';
export const WS_SEND_MESSAGE = 'WS_SEND_MESSAGE';
export const WS_UPDATE_CHAT = 'WS_UPDATE_CHAT';
export const WS_UPDATE_PROGRESS_VIDEO = 'WS_UPDATE_PROGRESS_VIDEO';

