export const SET_NAME = 'SET_NAME';
export const SET_IS_LOGGED = 'SET_IS_LOGGED';
export const SET_URL_VIDEO = 'SET_URL_VIDEO';
export const SET_SUGGESTED_VIDEOS = 'SET_SUGGESTED_VIDEOS';
export const SET_VIDEOS = 'SET_VIDEOS';
export const SET_LOADING_VIDEOS = 'SET_LOADING_VIDEOS';
