const ADD_VIDEO = 'WS_ADD_VIDEO';
const JOIN_ROOM = 'WS_JOIN_ROOM';
const UPDATE_ROOM = 'WS_UPDATE_ROOM';
const REMOVE_VIDEO = 'WS_REMOVE_VIDEO';
const VIEW_VIDEO = 'WS_VIEW_VIDEO';
const SEND_PLAYER_STATE = 'WS_SEND_PLAYER_STATE';
const NOTIFY_MESSAGE = 'WS_NOTIFY_MESSAGE';
const SEND_MESSAGE = 'WS_SEND_MESSAGE';
const UPDATE_CHAT = 'WS_UPDATE_CHAT';
const SEND_PROGRESS = 'WS_SEND_PROGRESS';
const REORDER_PLAYLIST = 'WS_REORDER_PLAYLIST';

module.exports = {
  UPDATE_ROOM,
  ADD_VIDEO,
  JOIN_ROOM,
  REMOVE_VIDEO,
  VIEW_VIDEO,
  SEND_PLAYER_STATE,
  NOTIFY_MESSAGE,
  SEND_MESSAGE,
  UPDATE_CHAT,
  SEND_PROGRESS,
  REORDER_PLAYLIST,
};
