name: Share videos CI pipeline for PRODUCTION

on:
  push:
    branches:
      - master

jobs:
  prepare-deploy:
    name: "Check which folders were modified"
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            server: 
              - 'server/**'
            frontend: 
              - 'frontend/**'

  deploy-server:
    name: Build server

    if: steps.changes.outputs.server == 'true'

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm i --no-audit --no-found --no-optional
      - name: Lint
        run: npm run lint
      - name: Run tests
        run: npm run test

  deploy-frontend:
    name: Build frontend

    if: steps.changes.outputs.frontend == 'true'

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm i --no-audit --no-found --no-optional
      - name: Lint
        run: npm run lint
      - name: Deploy to Vercel Action
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
