name: Share videos CI pipeline for PRODUCTION

on:
  push:
    branches:
      - master

jobs:
  deploy-server:
    name: Build server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            server: 
              - 'server/**'

      - name: Install dependencies
        if: steps.changes.outputs == 'true'
        run: npm ci --no-audit --no-found --no-optional
      - name: Lint
        if: steps.changes.outputs == 'true'
        run: npm run eslint
